with-expecter: true
packages:
  github.com/SKD-fastcampus/bot-management/services/notification/internal/domain/repository:
    interfaces:
      NotificationRepository:
        config:
          dir: services/notification/mocks
          outpkg: mocks
          filename: notification_repository.go
          mockname: MockNotificationRepository
  github.com/SKD-fastcampus/bot-management/services/notification/internal/usecase:
    interfaces:
      NotificationUsecase:
        config:
          dir: services/notification/mocks
          outpkg: mocks
          filename: notification_usecase.go
          mockname: MockNotificationUsecase
  github.com/SKD-fastcampus/bot-management/services/api/internal/domain/repository:
    interfaces:
      UserRepository:
        config:
          dir: services/api/mocks
          outpkg: mocks
          filename: user_repository.go
          mockname: MockUserRepository
  github.com/SKD-fastcampus/bot-management/services/api/internal/usecase:
    interfaces:
      UserUsecase:
        config:
          dir: services/api/mocks
          outpkg: mocks
          filename: user_usecase.go
          mockname: MockUserUsecase
  github.com/SKD-fastcampus/bot-management/services/auth/internal/domain/repository:
    interfaces:
      UserRepository:
        config:
          dir: services/auth/mocks
          outpkg: mocks
          filename: user_repository.go
          mockname: MockUserRepository
  github.com/SKD-fastcampus/bot-management/services/auth/internal/usecase:
    interfaces:
      AuthUsecase:
        config:
          dir: services/auth/mocks
          outpkg: mocks
          filename: auth_usecase.go
          mockname: MockAuthUsecase
  github.com/SKD-fastcampus/bot-management/pkg/messaging:
    interfaces:
      RedisClient:
        config:
          dir: pkg/messaging/mocks
          outpkg: mocks
          filename: redis_client.go
          mockname: MockRedisClient
  github.com/SKD-fastcampus/bot-management/services/bot-mgmt-server/internal/domain:
    interfaces:
      TaskRepository:
        config:
          dir: services/bot-mgmt-server/mocks
          outpkg: mocks
          filename: task_repository.go
          mockname: MockTaskRepository
      BotExecutor:
        config:
          dir: services/bot-mgmt-server/mocks
          outpkg: mocks
          filename: bot_executor.go
          mockname: MockBotExecutor 
  github.com/SKD-fastcampus/bot-management/services/bot-mgmt-server/internal/infrastructure/firebase:
    interfaces:
      TokenVerifier:
        config:
          dir: services/bot-mgmt-server/mocks
          outpkg: mocks
          filename: token_verifier.go
          mockname: MockTokenVerifier