// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/SKD-fastcampus/bot-management/services/bot-mgmt-server/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockBotExecutor is an autogenerated mock type for the BotExecutor type
type MockBotExecutor struct {
	mock.Mock
}

type MockBotExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBotExecutor) EXPECT() *MockBotExecutor_Expecter {
	return &MockBotExecutor_Expecter{mock: &_m.Mock}
}

// GetBotStatus provides a mock function with given fields: ctx, externalID
func (_m *MockBotExecutor) GetBotStatus(ctx context.Context, externalID string) (domain.TaskStatus, error) {
	ret := _m.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for GetBotStatus")
	}

	var r0 domain.TaskStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.TaskStatus, error)); ok {
		return rf(ctx, externalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.TaskStatus); ok {
		r0 = rf(ctx, externalID)
	} else {
		r0 = ret.Get(0).(domain.TaskStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBotExecutor_GetBotStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBotStatus'
type MockBotExecutor_GetBotStatus_Call struct {
	*mock.Call
}

// GetBotStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
func (_e *MockBotExecutor_Expecter) GetBotStatus(ctx interface{}, externalID interface{}) *MockBotExecutor_GetBotStatus_Call {
	return &MockBotExecutor_GetBotStatus_Call{Call: _e.mock.On("GetBotStatus", ctx, externalID)}
}

func (_c *MockBotExecutor_GetBotStatus_Call) Run(run func(ctx context.Context, externalID string)) *MockBotExecutor_GetBotStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBotExecutor_GetBotStatus_Call) Return(_a0 domain.TaskStatus, _a1 error) *MockBotExecutor_GetBotStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBotExecutor_GetBotStatus_Call) RunAndReturn(run func(context.Context, string) (domain.TaskStatus, error)) *MockBotExecutor_GetBotStatus_Call {
	_c.Call.Return(run)
	return _c
}

// RunBot provides a mock function with given fields: ctx, task
func (_m *MockBotExecutor) RunBot(ctx context.Context, task *domain.AnalysisTask) (string, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for RunBot")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AnalysisTask) (string, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AnalysisTask) string); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.AnalysisTask) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBotExecutor_RunBot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunBot'
type MockBotExecutor_RunBot_Call struct {
	*mock.Call
}

// RunBot is a helper method to define mock.On call
//   - ctx context.Context
//   - task *domain.AnalysisTask
func (_e *MockBotExecutor_Expecter) RunBot(ctx interface{}, task interface{}) *MockBotExecutor_RunBot_Call {
	return &MockBotExecutor_RunBot_Call{Call: _e.mock.On("RunBot", ctx, task)}
}

func (_c *MockBotExecutor_RunBot_Call) Run(run func(ctx context.Context, task *domain.AnalysisTask)) *MockBotExecutor_RunBot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.AnalysisTask))
	})
	return _c
}

func (_c *MockBotExecutor_RunBot_Call) Return(_a0 string, _a1 error) *MockBotExecutor_RunBot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBotExecutor_RunBot_Call) RunAndReturn(run func(context.Context, *domain.AnalysisTask) (string, error)) *MockBotExecutor_RunBot_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBotExecutor creates a new instance of MockBotExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBotExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBotExecutor {
	mock := &MockBotExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
