// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/SKD-fastcampus/bot-management/services/bot-mgmt-server/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, task
func (_m *MockTaskRepository) Create(ctx context.Context, task *domain.AnalysisTask) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AnalysisTask) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - task *domain.AnalysisTask
func (_e *MockTaskRepository_Expecter) Create(ctx interface{}, task interface{}) *MockTaskRepository_Create_Call {
	return &MockTaskRepository_Create_Call{Call: _e.mock.On("Create", ctx, task)}
}

func (_c *MockTaskRepository_Create_Call) Run(run func(ctx context.Context, task *domain.AnalysisTask)) *MockTaskRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.AnalysisTask))
	})
	return _c
}

func (_c *MockTaskRepository_Create_Call) Return(_a0 error) *MockTaskRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.AnalysisTask) error) *MockTaskRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveTaskByURL provides a mock function with given fields: ctx, url
func (_m *MockTaskRepository) GetActiveTaskByURL(ctx context.Context, url string) (*domain.AnalysisTask, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveTaskByURL")
	}

	var r0 *domain.AnalysisTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.AnalysisTask, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.AnalysisTask); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AnalysisTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_GetActiveTaskByURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveTaskByURL'
type MockTaskRepository_GetActiveTaskByURL_Call struct {
	*mock.Call
}

// GetActiveTaskByURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockTaskRepository_Expecter) GetActiveTaskByURL(ctx interface{}, url interface{}) *MockTaskRepository_GetActiveTaskByURL_Call {
	return &MockTaskRepository_GetActiveTaskByURL_Call{Call: _e.mock.On("GetActiveTaskByURL", ctx, url)}
}

func (_c *MockTaskRepository_GetActiveTaskByURL_Call) Run(run func(ctx context.Context, url string)) *MockTaskRepository_GetActiveTaskByURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskRepository_GetActiveTaskByURL_Call) Return(_a0 *domain.AnalysisTask, _a1 error) *MockTaskRepository_GetActiveTaskByURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_GetActiveTaskByURL_Call) RunAndReturn(run func(context.Context, string) (*domain.AnalysisTask, error)) *MockTaskRepository_GetActiveTaskByURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTaskRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.AnalysisTask, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.AnalysisTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.AnalysisTask, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.AnalysisTask); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AnalysisTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTaskRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTaskRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTaskRepository_GetByID_Call {
	return &MockTaskRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTaskRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTaskRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_GetByID_Call) Return(_a0 *domain.AnalysisTask, _a1 error) *MockTaskRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.AnalysisTask, error)) *MockTaskRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFailedTasks provides a mock function with given fields: ctx
func (_m *MockTaskRepository) GetFailedTasks(ctx context.Context) ([]*domain.AnalysisTask, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFailedTasks")
	}

	var r0 []*domain.AnalysisTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.AnalysisTask, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.AnalysisTask); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AnalysisTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_GetFailedTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFailedTasks'
type MockTaskRepository_GetFailedTasks_Call struct {
	*mock.Call
}

// GetFailedTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskRepository_Expecter) GetFailedTasks(ctx interface{}) *MockTaskRepository_GetFailedTasks_Call {
	return &MockTaskRepository_GetFailedTasks_Call{Call: _e.mock.On("GetFailedTasks", ctx)}
}

func (_c *MockTaskRepository_GetFailedTasks_Call) Run(run func(ctx context.Context)) *MockTaskRepository_GetFailedTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTaskRepository_GetFailedTasks_Call) Return(_a0 []*domain.AnalysisTask, _a1 error) *MockTaskRepository_GetFailedTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_GetFailedTasks_Call) RunAndReturn(run func(context.Context) ([]*domain.AnalysisTask, error)) *MockTaskRepository_GetFailedTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingTasks provides a mock function with given fields: ctx
func (_m *MockTaskRepository) GetPendingTasks(ctx context.Context) ([]*domain.AnalysisTask, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingTasks")
	}

	var r0 []*domain.AnalysisTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.AnalysisTask, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.AnalysisTask); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AnalysisTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_GetPendingTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingTasks'
type MockTaskRepository_GetPendingTasks_Call struct {
	*mock.Call
}

// GetPendingTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskRepository_Expecter) GetPendingTasks(ctx interface{}) *MockTaskRepository_GetPendingTasks_Call {
	return &MockTaskRepository_GetPendingTasks_Call{Call: _e.mock.On("GetPendingTasks", ctx)}
}

func (_c *MockTaskRepository_GetPendingTasks_Call) Run(run func(ctx context.Context)) *MockTaskRepository_GetPendingTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTaskRepository_GetPendingTasks_Call) Return(_a0 []*domain.AnalysisTask, _a1 error) *MockTaskRepository_GetPendingTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_GetPendingTasks_Call) RunAndReturn(run func(context.Context) ([]*domain.AnalysisTask, error)) *MockTaskRepository_GetPendingTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetRunningTasks provides a mock function with given fields: ctx
func (_m *MockTaskRepository) GetRunningTasks(ctx context.Context) ([]*domain.AnalysisTask, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRunningTasks")
	}

	var r0 []*domain.AnalysisTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.AnalysisTask, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.AnalysisTask); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AnalysisTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_GetRunningTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRunningTasks'
type MockTaskRepository_GetRunningTasks_Call struct {
	*mock.Call
}

// GetRunningTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskRepository_Expecter) GetRunningTasks(ctx interface{}) *MockTaskRepository_GetRunningTasks_Call {
	return &MockTaskRepository_GetRunningTasks_Call{Call: _e.mock.On("GetRunningTasks", ctx)}
}

func (_c *MockTaskRepository_GetRunningTasks_Call) Run(run func(ctx context.Context)) *MockTaskRepository_GetRunningTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTaskRepository_GetRunningTasks_Call) Return(_a0 []*domain.AnalysisTask, _a1 error) *MockTaskRepository_GetRunningTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_GetRunningTasks_Call) RunAndReturn(run func(context.Context) ([]*domain.AnalysisTask, error)) *MockTaskRepository_GetRunningTasks_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, task
func (_m *MockTaskRepository) Update(ctx context.Context, task *domain.AnalysisTask) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AnalysisTask) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - task *domain.AnalysisTask
func (_e *MockTaskRepository_Expecter) Update(ctx interface{}, task interface{}) *MockTaskRepository_Update_Call {
	return &MockTaskRepository_Update_Call{Call: _e.mock.On("Update", ctx, task)}
}

func (_c *MockTaskRepository_Update_Call) Run(run func(ctx context.Context, task *domain.AnalysisTask)) *MockTaskRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.AnalysisTask))
	})
	return _c
}

func (_c *MockTaskRepository_Update_Call) Return(_a0 error) *MockTaskRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.AnalysisTask) error) *MockTaskRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
